language: python

cache:
  directories:
    - $HOME/.cache/pip

env:
  global:
    - DJANGO_SETTINGS_MODULE=autofixture_tests.settings
  matrix:
    - TOX_ENV=docs
    - TOX_ENV=py26-14
    - TOX_ENV=py26-15
    - TOX_ENV=py26-16
    - TOX_ENV=py27-14
    - TOX_ENV=py27-15
    - TOX_ENV=py27-16
    - TOX_ENV=py27-17
    - TOX_ENV=py33-16
    - TOX_ENV=py33-17
    - TOX_ENV=py34-16
    - TOX_ENV=py34-17
    - TOX_ENV=pypy-14
    - TOX_ENV=pypy-15
    - TOX_ENV=pypy-16
    - TOX_ENV=pypy-17

install:
  - pip install pip wheel -U
  - pip install tox
script:
  - tox -e $TOX_ENV -v
